language: python
dist: trusty
matrix:
  include:
    - python: pypy-5.4.1
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 2.7
    - python: 3.5
    - python: 3.6
install:
- pip install -rrequirements-dev.txt coveralls
script:
- COVERAGE_PROCESS_START=$PWD/.coveragerc pytest sasstests.py
- coverage combine
- coverage report
- pre-commit run --all-files --show-diff-on-failure
after_success:
- coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
